# Generated by Django 5.1 on 2024-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_productimage_image_route_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
