# Generated by Django 5.1 on 2024-09-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_productos_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
    ]
